services:
  archi_health_tracker:
    image: archi_health_tracker
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - ConnectionStrings__Database=Server=db;Database=${MYSQL_DATABASE};Uid=${MYSQL_USER};Pwd=${MYSQL_PASSWORD};CharSet=utf8mb4;
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Production}
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - "8080:5000"
    volumes:
      - ./appsettings.json:/app/appsettings.json:ro
    
    depends_on:
      db:
        condition: service_healthy
  
  db:
    image: mysql:8.0
    container_name: archie_mysql
    restart: always
    command: [
      "mysqld",
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci"
    ]
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

volumes:
  db_data:

    